# $Id: Makefile 2395 2006-11-02 09:34:16Z magicyang $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o misc.o \
	   tree.o console.o printf.o p1275.o cif.o
